### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by haesleinhuepf** [ctr26/pytorch_tutorial#1]
Hi @ctr26 ,

this is an amazing resource! Thanks for sharing openly! I was just wondering under which conditions one could reuse the materials and code provided here. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by ctr26** [comment]
Hi Robert,

Thanks for reaching out, 

I've added the MIT license,

Let me know if there's anything you'd like to see adding to the tutorial,

Thanks

Craig

**Comment by haesleinhuepf** [comment]
Fantastic! Thanks so much for the lightspeed response!
